#!/bin/bash
## Change the wallpaper on XFCE4.
## Run "xfconf-query -c xfce4-desktop -m" and change your wallpaper manually to see which change you need to make to this script.

WALLPAPERS_FOLDER="/Pictures/Backgrounds/Raw_Wallpapers/"
DISPLAY_1="HDMI-A-0"

xfconf-query --channel xfce4-desktop --property /backdrop/screen0/monitor${DISPLAY_1}/workspace0/last-image --set $(echo ${HOME}/${WALLPAPERS_FOLDER}/$(ls ${HOME}/${WALLPAPERS_FOLDER} | shuf | head -n 1))
