#!/bin/bash
## Find pictures with a high level of certain color.

## TODO:
## - check if the RGB value is "+250" instead of "255".
## - "--no-prompt" switch (for removal).

## Set colors.
BLUE="\e[34m"
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
GREY="\e[37m"
BOLD="\e[1m"
RC="\e[0m"

if [[ ${1} ]]
	then
		PIC_FOLDER=${1}
	else
		echo -e "${WARN}Please, specify a folder containing pictures!"
		exit 1
fi

WHITE="255,255,255"
BLACK="0,0,0"
FIND_COLOR=${WHITE}

## Print the RBG value of the prominent color of pictures in the specified folder.
for FILE in $(ls ${PIC_FOLDER})
	do
		VALUE=$(convert ${PIC_FOLDER}/${FILE} -colorspace RGB -format %c histogram:info:-\
		| sort -nr \
		| head -n 1 \
		| awk -F'[()]' '{print $2}')
		echo -e "${INFO}${PIC_FOLDER}/${FILE}: ${GREY}${VALUE}"
			if [[ ${VALUE} == ${FIND_COLOR} ]]
				then
					echo -e "${INFO}The picture \e[4m${FILE}${INFO}mostly contain the white color.\nRemove it? (y/n)"
					read REMOVE
						case ${REMOVE} in
							y|Y)
								rm ${PIC_FOLDER}/${FILE} && echo -e "${GOOD}Picture ${FILE} removed!" || echo -e "${WARN}Something went wrong!"
								;;
							n|N)
								echo -e "${INFO}Skipping this file..."
								;;
							*)
								exit 1
								;;
						esac
			fi

done
