#!/bin/bash
## Download wallpapers from
## - https://wallhaven.cc
## Heavily inspired by BugsWriter video's (https://www.youtube.com/watch?v=Ol3g0Rp0XkM)

## TODO:
## - Remove the brighter ones?
## - Downloads images from more sites.
## - Get the page number before shuf and download.

RESET_COLOR="\e[0m"
GREEN="\e[32m"
YELLOW="\e[33m"
RED="\e[31m"
BOLD="\e[1m"

REQUIREMENTS="curl jq notify-send"

WALLPAPERS_DIR="${HOME}/Pictures/Backgrounds/Raw_Wallpapers"
MIN_RESOLUTION="1920x1080"
SORT_OPTIONS="relevance" ## date_added relevance random views favorites toplist.
QUERY="${1}"
PAGE=$(shuf -i 1-2748 | head -n1) ## 2748 pages for "girl" in anime (02/08/2021).
## Turn categories on(1) or off(0).
CATEGORY="010" ## 100/101/111*/etc (general/anime/people).
## Turn purities on(1) or off(0) NSFW requires a valid API key.
PURITY="110" ##100*/110/111/etc (sfw/sketchy/nsfw).

## Change input to URL format.
QUERY="$(sed 's/#//g' <<<${QUERY})"
QUERY="$(sed 's/ /+/g' <<<${QUERY})"

mkdir -p ${WALLPAPERS_DIR}

WALLHAVEN_URL="https://wallhaven.cc/api/v1/search?q=${QUERY}&categories=${CATEGORY}&purity=${PURITY}&sorting=${SORT_OPTIONS}&order=desc&page=${PAGE}"

function WALLHAVEN_REQUEST()
{
	curl -sf ${WALLHAVEN_URL}\
	| jq '.' | grep -Eoh 'https:\/\/w\.wallhaven.cc\/full\/.*(jpg|png)\b'\
	| xargs -l wget -nc -nv -P ${WALLPAPERS_DIR}
}

function OPEN_FILE_MANAGER()
{
	echo -e "${YELLOW}Open the wallpaper directory? (N/y)${RESET_COLOR}"
	read -s -t 3 OPEN
		if [[ ${OPEN} == "y" ]]
			then
				exo-open --launch FileManager ${HOME}/Pictures/Backgrounds/Raw_Wallpapers 2>/dev/null
					if [[ ${?} -eq "0" ]]
						then
							exit 0
						else
							echo "${RED}Unable to find a file manager!\nExiting...${RESET_COLOR}"
							exit 1
					fi
			else
				exit 0
		fi
}

if [[ ${1} ]]
	then
		which ${REQUIREMENTS} > /dev/null
		if [[ ${?} -eq "0" ]]
			then
				echo -e " 🔎 ${YELLOW}Searching for ${QUERY} wallpapers...${RESET_COLOR}"
				WALLHAVEN_REQUEST
					if [[ ${?} -ne "0" ]]
						then
							echo -e "${RED}Page not found...${RESET_COLOR}"
						else
							notify-send " ✅ Wallpapers downloads finished! "
							OPEN_FILE_MANAGER
					fi

			else
				echo -e "${RED}To run this program, you need the following packages installed: ${BOLD}${REQUIREMENTS}\nExiting...${RESET_COLORS}"
				exit 1
		fi
	else
		echo -e "${RED}Please, provides a topics for your images (e.g. Cars)\nExiting..."
fi
