#!/bin/bash
## Download wallpapers from:
## - https://wallhaven.cc

## Heavily inspired by BugsWriter video's (https://www.youtube.com/watch?v=Ol3g0Rp0XkM)
## See the wallhaven API documentation "https://wallhaven.cc/help/api"

## TODO:
## - Downloads images from more sites.
## - Get the page number before shuf and download. (*1)

## Set colors.
RC="\e[0m"
BOLD="\e[1m"
GREEN="\e[32m"
RED="\e[31m"
BLUE="\e[34m"

WARN="${RED}${BOLD} [-] ${RC}"
INFO="${BLUE}${BOLD} [*] ${RC}"
GOOD="${GREEN}${BOLD} [+] ${RC}"

REQUIREMENTS="curl jq notify-send"

WALLPAPERS_DIR=${2}
MIN_RESOLUTION="1920x1080"
SORT_OPTIONS="relevance" ## valid options are: "date_added" "relevance" "random" "views" "favorites" "toplist".
QUERY="${1}"
PAGE=$(shuf -i 1-1626 | head -n1) ## Numbers of pages to search.
## Turn categories on(1) or off(0).
CATEGORY="001" ## 100/101/111*/... (general/anime/people).
## Turn purities on(1) or off(0) NSFW requires a valid API key.
PURITY="100" ##100/110/111/... (sfw/sketchy/nsfw).

## Change input to URL format.
QUERY="$(sed 's/#//g' <<<${QUERY})"
QUERY="$(sed 's/ /+/g' <<<${QUERY})"

mkdir -p ${WALLPAPERS_DIR}

WALLHAVEN_URL="https://wallhaven.cc/api/v1/search?q=${QUERY}&categories=${CATEGORY}&purity=${PURITY}&sorting=${SORT_OPTIONS}&order=desc&page=${PAGE}"

WALLHAVEN_REQUEST()
{
	curl -sf ${WALLHAVEN_URL}\
	| jq '.' | grep -Eoh 'https:\/\/w\.wallhaven.cc\/full\/.*(jpg|png)\b'\
	| xargs -l wget -nc -nv -P ${WALLPAPERS_DIR}
}

if [[ ${1} && ${2} ]]
	then
		which ${REQUIREMENTS} > /dev/null
		if [[ ${?} -eq "0" ]]
			then
				echo -e " 🔎 ${INFO}Searching for ${QUERY} wallpapers..."
				WALLHAVEN_REQUEST
					if [[ ${?} -ne "0" ]]
						then
							echo -e "${WARN}Page not found..."
						else
							notify-send " ✅ Wallpapers downloads done! "
					fi

			else
				echo -e "${WARN}To run this program, you need the following packages installed: ${REQUIREMENTS}"
				exit 1
		fi
	else
		echo -e "${WARN}Please, provides a topics for your images (e.g. Cars)"
fi
